CREATE TABLE TEST_ALL_TYPE (
ID INTEGER PRIMARY KEY,
V_TINYINT TINYINT,
V_BIT BIT,
V_BOOL BOOL,
V_SMALLINT SMALLINT,
V_MEDIUMINT MEDIUMINT,
V_INT INT,
V_INTEGER INTEGER,
V_BIGINT BIGINT,
V_FLOAT FLOAT,
V_DOUBLE DOUBLE,
V_DOUBLE_PRECISION DOUBLE PRECISION,
V_REAL REAL,
V_DECIMAL DECIMAL(10,4),
V_Dec Dec(10,4),
V_NUMERIC NUMERIC(10,4),
V_DATE DATE,
V_DATETIME DATETIME,
V_TIMESTAMP TIMESTAMP,
V_TIME TIME,
V_YEAR YEAR,
V_CHAR CHAR(20),
V_VARCHAR VARCHAR(20),
V_TINYBLOB TINYBLOB,
V_TINYTEXT TINYTEXT,
V_BLOB  BLOB ,
V_TEXT TEXT,
V_MEDIUMBLOB MEDIUMBLOB,
V_MEDIUMTEXT MEDIUMTEXT,
V_LONGBLOB  LONGBLOB ,
V_LONGTEXT LONGTEXT,
V_ENUM ENUM('E1','E2','E3'),
V_SET SET('S1','S2','S3')
)

;

INSERT INTO
	TEST_ALL_TYPE
(
	ID,
	V_TINYINT,
	V_BIT,
	V_BOOL,
	V_SMALLINT,
	V_MEDIUMINT,
	V_INT,
	V_INTEGER,
	V_BIGINT,
	V_FLOAT,
	V_DOUBLE,
	V_DOUBLE_PRECISION,
	V_REAL,
	V_DECIMAL,
	V_Dec,
	V_NUMERIC,
	V_DATE,
	V_DATETIME,
	V_TIMESTAMP,
	V_TIME,
	V_YEAR,
	V_CHAR,
	V_VARCHAR,
	V_TINYBLOB,
	V_TINYTEXT,
	V_BLOB,
	V_TEXT,
	V_MEDIUMBLOB,
	V_MEDIUMTEXT,
	V_LONGBLOB,
	V_LONGTEXT,
	V_ENUM,
	V_SET
)
VALUES
(
	'1',	/* ID */
	'10',	/* V_TINYINT */
	1,	/* V_BIT */
	TRUE,	/* V_BOOL */
	'11',	/* V_SMALLINT */
	'12',	/* V_MEDIUMINT */
	'13',	/* V_INT */
	'14',	/* V_INTEGER */
	'15',	/* V_BIGINT */
	'0.1612345',	/* V_FLOAT */
	'0.1712345',	/* V_DOUBLE */
	'0.1812345',	/* V_DOUBLE_PRECISION */
	'1234.5678',	/* V_REAL */
	'2234.5678',	/* V_DECIMAL */
	'3234.5678',	/* V_Dec */
	'4234.5678',	/* V_NUMERIC */
	NOW(),	/* V_DATE */
	NOW(),	/* V_DATETIME */
	NOW(),	/* V_TIMESTAMP */
	NOW(),	/* V_TIME */
	2009,	/* V_YEAR */
	'char',	/* V_CHAR */
	'varchar',	/* V_VARCHAR */
	'tinyblob',	/* V_TINYBLOB */
	'tinytext',	/* V_TINYTEXT */
	'blob',	/* V_BLOB */
	'text',	/* V_TEXT */
	'mediumblob',	/* V_MEDIUMBLOB */
	'mediumtext',	/* V_MEDIUMTEXT */
	'longblob',	/* V_LONGBLOB */
	'longtext',	/* V_LONGTEXT */
	'E1',	/* V_ENUM */
	'S1'	/* V_SET */
)
